# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Workspace/F16genesisfinal/VDP/VSG.srcs/sources_1/ip/obj_info_RAM/obj_info_RAM.xci
# IP: The module: 'obj_info_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/F16genesisfinal/VDP/VSG.srcs/sources_1/ip/obj_info_RAM/obj_info_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'obj_info_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Workspace/F16genesisfinal/VDP/VSG.srcs/sources_1/ip/obj_info_RAM/obj_info_RAM.xci
# IP: The module: 'obj_info_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/F16genesisfinal/VDP/VSG.srcs/sources_1/ip/obj_info_RAM/obj_info_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'obj_info_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
